spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT:913103db4644c9da634b}
            client-secret: ${GITHUB_SECRET:c6d075265346833c05acc276df4b4c95a91b22df}
            scope: user:email
cloudinary:
  cloud-name: dowdh8mbc
  api-key: 697186739998891
  api-secret: wONlWV5n5E3DvvZG05beJHu71ic

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
app:
  default:
    password: pass

mail:
  project: "project@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USER:user}
  password:  ${MAIL_PASS:pass}
marketplace:
  remember.me.key: ${REMEMBER_ME_KEY:topsecret}
server:
  error:
    include-stacktrace: always
